#!/usr/bin/env python3
"""Cut the offline suite's fixtures out of real captures, and PROVE they parse
the same.

Its output is `fixtures_generated.json`, which `smoke_test.py` loads.

WHY A GENERATED FILE RATHER THAN INLINE LITERALS
------------------------------------------------
The family's rule is fixtures inline in `smoke_test.py`. Here a capture is a
whole page: a Listopia page is 780 KB and a book page 750 KB, most of it ads,
scripts and CSRF-bearing forms. Pasting even a trimmed one into a Python
source file would make the suite unreadable. The generated JSON sits beside
it, is regenerated by this script, and is checked by the suite for the same
properties inline fixtures would be (rakuten, polymarket and binance do the
same for the same reason).

WHAT YOU NEED TO RUN IT
-----------------------
Your own captures, in `captures/` (ignored by git), named as the SOURCES
table below expects. Take them with `--dump-html`, which writes exactly the
document the parser was given.

WHAT IT ENFORCES
----------------
  * every fixture is CUT from a real capture: the parts the parser reads,
    verbatim, inside a minimal document. Nothing is hand-written except the
    placeholders the scrub puts in;
  * each one parses IDENTICALLY to the untrimmed original for the records
    it keeps, every column, apart from the columns the scrub replaced, and
    states the same page state, served page, page count and total;
  * the scrub runs BEFORE anything is embedded:
      - the AppSync key the book page hands every visitor (`pageProps.apiKey`)
        and every CSRF `authenticity_token`. Neither grants anything to a
        reader of this repo, and neither belongs in it (§10);
      - a reviewer's name, profile id and url, and the review's own text and
        id. The checks need the STRUCTURE of a review, not a person's words
        (§10). Book, author and series data is the site's catalogue and is
        kept verbatim;
  * a fixture that still holds a 32-hex string, a `da2-` key or a CSRF token
    after the scrub is refused.

NOT VERBATIM: the search fixtures' React payload is RE-ENCODED. The page
streams ~250 KB of React Server Components data, and the fixture carries the
same Book objects the parser merged out of it, re-serialised as one push
chunk. The parser's path through it (decode the pushes, raw-decode each Book)
is the same; the byte layout is not.

    python3 make_fixtures.py [captures_dir]
"""
import copy
import json
import pathlib
import re
import sys
from dataclasses import asdict

REPO = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(REPO))

import product_parser as P  # noqa: E402

HEX32 = re.compile(r"\b[0-9a-f]{32}\b")
APPSYNC_KEY = re.compile(r"da2-[a-z0-9]{20,}")
CSRF = re.compile(r"authenticity_token")
# `REDACTED-` is the prefix the credential scan's key-shaped-field rule
# knows as a placeholder, so the fixture needs no exemption of its own.
PLACEHOLDER_KEY = "REDACTED-appsync-key"

GR = "https://www.goodreads.com"

# name -> (capture, url it was fetched at, records kept, kind, status)
SOURCES = {
    "list_p1": ("list_1_p1.html", GR + "/list/show/1.Best_Books_Ever", 5, "microdata", 200),
    "list_p2": ("list_1_p2.html", GR + "/list/show/1.Best_Books_Ever?page=2", 3, "microdata", 200),
    "list_p800": ("list_1_p800.html", GR + "/list/show/1.Best_Books_Ever?page=800", 2, "microdata", 200),
    "author_p1": ("author_656983_p1.html", GR + "/author/list/656983.J_R_R_Tolkien", 4, "microdata", 200),
    "search_legacy": ("search_dune_legacy.html", GR + "/search?q=dune", 3, "microdata", 200),
    "search_p2": ("search_dune_p2.html", GR + "/search?q=dune&page=2", 4, "rsc", 200),
    "search_p999": ("search_dune_p999.html", GR + "/search?q=dune&page=999", 2, "rsc", 200),
    "shelf_p1": ("shelf_fantasy_p1.html", GR + "/shelf/show/fantasy", 3, "shelf", 200),
    "series": ("series_66175.html", GR + "/series/66175-the-lord-of-the-rings", None, "series", 200),
    "book_hobbit": ("book_5907.html", GR + "/book/show/5907.The_Hobbit", None, "book", 200),
    "book_dune": ("book_44767458_browser.html", GR + "/book/show/44767458-dune", None, "book", 200),
    "book_missing": ("book_missing.html", GR + "/book/show/999999999999", None, "book", 200),
    "reviews_p1": ("reviews_5907_p1.json", GR + "/book/show/5907", 4, "reviews", 200),
    "reviews_p2": ("reviews_5907_p2.json", GR + "/book/show/5907", 2, "reviews", 200),
    "reviews_fr_1star": ("reviews_5907_fr_1star.json", GR + "/book/show/5907", 3, "reviews", 200),
    "reviews_xx": ("reviews_5907_xx.json", GR + "/book/show/5907", 0, "reviews", 200),
    "reviews_401": ("reviews_401.json", P.GRAPHQL_ENDPOINT, 0, "raw", 401),
    "reviews_bad_sort": ("reviews_bad_sort.json", P.GRAPHQL_ENDPOINT, 0, "raw", 200),
    "author_p999": ("author_656983_p999.html", GR + "/author/list/656983.J_R_R_Tolkien?page=999", 0, "notfound", 404),
    "search_none": ("search_none.html", GR + "/search?q=zzqxqzzqxkjh", 0, "none", 200),
}
# Captures that exist only on some machines (the WAF's own page must be
# caught in the second before its script reloads it). Cut when present.
OPTIONAL = {
    "waf_challenge": ("waf_challenge.html", GR + "/book/show/5907", 0, "waf", None),
    # A book page fetched over --cdp-endpoint (2026-09-28, a country-us
    # profile). The Scraping Browser's auto-solve extension injects the same
    # captcha hunters into EVERY page it loads (§24): 16 scripts here,
    # amazon_waf among them, plus a `<captcha-widgets>` mount. Cut like any
    # book page, with the injected tags kept verbatim; the markers must score
    # zero on it WITHOUT any strip.
    "cdp_book": ("cdp_book_5907.html", GR + "/book/show/5907.The_Hobbit", None, "cdp", 200),
}


def _doc(title: str, body: str, head_extra: str = "") -> str:
    # The asset reference is the one every served page carries (9 to 298
    # times per capture); the classifier's served-page check reads it.
    return ('<!DOCTYPE html><html><head><title>%s</title>'
            '<link rel="stylesheet" href="https://s.gr-assets.com/assets/cut.css">'
            '%s</head><body>%s</body></html>' % (title, head_extra, body))


def _title(html: str) -> str:
    m = re.search(r"<title>(.*?)</title>", html, re.S)
    return m.group(1).strip() if m else ""


def _strip_forms(fragment: str) -> str:
    """Tiles carry shelf buttons: forms with a CSRF token and inline JS with
    another. The parser reads neither, so both go. Asset urls carry a
    32-hex build fingerprint (`loading-trans-<md5>.gif`), which is the shape
    of an API key and would teach the credential scan an exception, so the
    fingerprint goes too (§24: take it out rather than exempt it)."""
    fragment = re.sub(r"-[0-9a-f]{32}(\.[a-z]+)", r"\1", fragment)
    fragment = re.sub(r"<form\b.*?</form>", "", fragment, flags=re.S)
    fragment = re.sub(r"<script\b.*?</script>", "", fragment, flags=re.S)
    fragment = re.sub(r'<a [^>]*onclick="[^"]*authenticity_token[^"]*"[^>]*>',
                      '<a href="#">', fragment)
    return fragment


def _cut_microdata(html: str, keep: int) -> str:
    soup = P._soup(html)
    tiles = [_strip_forms(str(t)) for t in P._microdata_tiles(soup)[:keep]]
    box = P._pagination(html)
    pag = "<div>%s</div>" % re.sub(r"\s+", " ", str(box)) if box is not None else ""
    return _doc(_title(html), "<table>%s</table>%s" % ("".join(tiles), pag))


def _cut_shelf(html: str, keep: int) -> str:
    soup = P._soup(html)
    shown = re.search(r"Showing\s+[\d,]+\s*-\s*[\d,]+\s+of\s+[\d,]+", P._text(soup) or "")
    els = [_strip_forms(str(e)) for e in soup.select("div.elementList")[:keep]]
    return _doc(_title(html), "<div>%s</div>%s" % (shown.group(0) if shown else "", "".join(els)))


def _cut_series(html: str) -> str:
    parts = ['<div data-react-class="ReactComponents.SeriesList" data-react-props="%s"></div>' % p
             for p in P._SERIES_PROPS_RE.findall(html)]
    heads = P._SERIES_HEADER_RE.findall(html)
    sub = P._SERIES_WORKS_RE.search(html)
    body = "<div>%s</div>" % (sub.group(0) if sub else "")
    body += "".join("<h3>%s</h3>" % h for h in heads) + "".join(parts)
    return _doc(_title(html), body)


def _cut_rsc(html: str, keep: int) -> str:
    books = P._rsc_books(html)[:keep]
    flight = "".join(json.dumps(b, ensure_ascii=False, separators=(",", ":")) for b in books)
    push = "<script>self.__next_f.push([1,%s])</script>" % json.dumps(flight, ensure_ascii=False)
    page_of = P._PAGE_OF_RE.search(html)
    return _doc(_title(html), "<div>%s</div>%s" % (page_of.group(0) if page_of else "", push))


def _cut_book(html: str) -> str:
    """The book's own entities out of the Apollo cache, the key replaced."""
    nd = P.next_data(html)
    ap = P._apollo(nd)
    root = ap.get("ROOT_QUERY") or {}
    keep_root = {k: v for k, v in root.items()
                 if k == "__typename" or k.startswith(("getBookByLegacyId", "getSocialSignals"))}
    wanted = set()

    def refs(v):
        if isinstance(v, dict):
            if "__ref" in v and v["__ref"] not in wanted:
                wanted.add(v["__ref"])
                refs(ap.get(v["__ref"]))
            for x in v.values():
                refs(x)
        elif isinstance(v, list):
            for x in v:
                refs(x)

    refs(keep_root)
    ap2 = {"ROOT_QUERY": keep_root}
    for k in sorted(wanted):
        if k.startswith("User:"):
            # A Work's featured-notes creator is a person, not catalogue.
            continue
        ent = copy.deepcopy(ap[k])
        if k.startswith("Work:"):
            ent.pop("featuredKNH", None)
            ent.pop("giveaways", None)
        if k.startswith("Book:"):
            ent.pop("links", None)
        ap2[k] = ent
    pp = nd["props"]["pageProps"]
    nd2 = {"props": {"pageProps": {"apolloState": ap2, "params": pp.get("params"),
                                   "apiKey": PLACEHOLDER_KEY if pp.get("apiKey") else None}},
           "page": nd.get("page")}
    head = "".join('<script type="application/ld+json">%s</script>' % x
                   for x in P._JSONLD_RE.findall(html))
    body = '<script id="__NEXT_DATA__" type="application/json">%s</script>' % json.dumps(
        nd2, ensure_ascii=False)
    return _doc(_title(html), body, head)


_REVIEW_TEXTS = (
    "<b>Placeholder review.</b> The first paragraph of a review, standing in "
    "for a reader's words.<br /><br />A second paragraph after a break.",
    "A one-line placeholder review.",
    "<blockquote>A quoted opening line.</blockquote>Placeholder text after it.",
)


def _cut_reviews(text: str, keep: int) -> str:
    payload = json.loads(text)
    block = payload["data"]["getReviews"]
    block["edges"] = block["edges"][:keep]
    for i, e in enumerate(block["edges"], 1):
        n = e["node"]
        n["id"] = "kca://review:goodreads/amzn1.gr.review:goodreads.v1.PLACEHOLDER%03d" % i
        n["text"] = _REVIEW_TEXTS[(i - 1) % len(_REVIEW_TEXTS)]
        n["shelving"]["webUrl"] = GR + "/review/show/%d" % (900000000 + i)
        c = n.get("creator") or {}
        c["id"] = "kca://profile:goodreads/PLACEHOLDER%03d" % i
        c["legacyId"] = 100000000 + i
        c["name"] = "Reviewer %d" % i
        c["webUrl"] = GR + "/user/show/%d-reviewer-%d" % (100000000 + i, i)
    if (block.get("pageInfo") or {}).get("nextPageToken"):
        # Opaque and harmless, but a real cursor is a real position in a
        # real feed; any non-empty string exercises the same path.
        block["pageInfo"]["nextPageToken"] = "UExBQ0VIT0xERVI"
    return json.dumps(payload, ensure_ascii=False)


def _cut_waf(html: str) -> str:
    # The WAF's page is a few KB of its own markup, kept whole, with any
    # token-shaped value in it replaced.
    return re.sub(r'"(key|iv|context)"\s*:\s*"[^"]*"', r'"\1":"PLACEHOLDER"', html)


_EXT_TAG_RE = re.compile(r'<script[^>]*chrome-extension://[^>]*>\s*</script>|<captcha-widgets[^>]*>\s*</captcha-widgets>')


def _cut_cdp(html: str) -> str:
    """A book page cut as usual, with what the extension injected kept."""
    return _cut_book(html).replace("</head>", "".join(_EXT_TAG_RE.findall(html)) + "</head>", 1)


def _scrub_problems(fixture: str) -> list:
    problems = []
    if HEX32.search(fixture):
        problems.append("a 32-hex string")
    if APPSYNC_KEY.search(fixture):
        problems.append("an AppSync key")
    if CSRF.search(fixture):
        problems.append("a CSRF token")
    return problems


REPLACED = {"reviews": {"url", "sku", "text", "reviewer", "reviewer_id", "reviewer_url"}}


def _query(url: str, kind: str):
    if kind in ("reviews", "raw") and "appsync" in url:
        q, _ = P.query_from_url(GR + "/book/show/5907")
    else:
        q, _ = P.query_from_url(url)
    if kind == "reviews":
        q.mode = "reviews"
    return q


def _compare(orig, cut, kind, url, status) -> list:
    q = _query(url, kind)
    where = P.GRAPHQL_ENDPOINT if kind == "reviews" else url
    diffs = []
    s1, s2 = P.detect_page_state(orig, status, where), P.detect_page_state(cut, status, where)
    if s1 != s2:
        diffs.append("state %s != %s" % (s1, s2))
    if kind in ("raw", "waf"):
        return diffs
    if kind == "cdp":
        kind = "book"
    r1 = [asdict(r) for r in P.parse_page(orig, q, 1)]
    r2 = [asdict(r) for r in P.parse_page(cut, q, 1)]
    if len(r2) > len(r1):
        diffs.append("the cut holds more rows than the original")
    skip = {"scraped_at"} | REPLACED.get(kind, set())
    for a, b in zip(r1, r2):
        for k in a:
            if k not in skip and a[k] != b[k]:
                diffs.append("%s: %r != %r" % (k, a[k], b[k]))
    if kind in ("microdata", "rsc", "shelf", "series"):
        for fn in (P.served_page, P.pages_available, P.total_results):
            if fn(orig, q.kind) != fn(cut, q.kind):
                diffs.append("%s %r != %r" % (fn.__name__, fn(orig, q.kind), fn(cut, q.kind)))
    if kind == "book":
        a, b = P.book_landing(orig), P.book_landing(cut)
        a.pop("api_key")
        b.pop("api_key")
        if a != b:
            diffs.append("book_landing differs")
    return diffs


CUTTERS = {
    "microdata": lambda h, k: _cut_microdata(h, k), "shelf": lambda h, k: _cut_shelf(h, k),
    "series": lambda h, k: _cut_series(h), "rsc": lambda h, k: _cut_rsc(h, k),
    "book": lambda h, k: _cut_book(h), "reviews": lambda h, k: _cut_reviews(h, k),
    "notfound": lambda h, k: _doc(_title(h), "<h1>Page not found</h1>"),
    "none": lambda h, k: _doc(_title(h), "<div>No results.</div>"),
    "waf": lambda h, k: _cut_waf(h), "raw": lambda h, k: h,
    "cdp": lambda h, k: _cut_cdp(h),
}


def main(argv) -> int:
    cap = pathlib.Path(argv[1] if len(argv) > 1 else REPO / "captures")
    out, bad = {}, 0
    sources = dict(SOURCES)
    sources.update({k: v for k, v in OPTIONAL.items() if (cap / v[0]).exists()})
    for name, (fname, url, keep, kind, status) in sources.items():
        orig = (cap / fname).read_text(encoding="utf-8")
        cut = CUTTERS[kind](orig, keep)
        problems = _compare(orig, cut, kind, url, status) + _scrub_problems(cut)
        if problems:
            bad += 1
            print("FAIL %s: %s" % (name, "; ".join(problems)[:600]))
            continue
        out[name] = {"url": url, "status": status, "text": cut}
        print("ok   %-18s %7d -> %6d bytes" % (name, len(orig), len(cut)))
    if bad:
        print("%d fixture(s) refused; nothing written." % bad)
        return 1
    path = REPO / "fixtures_generated.json"
    path.write_text(json.dumps(out, ensure_ascii=False, indent=1, sort_keys=True) + "\n",
                    encoding="utf-8")
    print("wrote %s (%d fixtures)" % (path.name, len(out)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
